### ISSUE TITLE
超过屏幕高度的网络图片，下拉无法关闭

### ISSUE THREAD

**Issue by yanmingLiu** [fcbox/Lantern#8]
demo中Kingfisher 加载示例中 KingfisherImageViewController：
1. 修改图片源地址为长图：             let url = URL(string: "https://ewow-community.epal.gg/data/IdfF31E0/community/1614666157363137079773003777.png")

2. 双指放大图片
3. 缩小图片到原始状态
4. 下拉， 无法关闭！！！

问题在缩放图片后， scrollView.contentOffset.y > 0： 代码问题如下：

 // 向下滑动，如果图片顶部超出可视区域，不响应手势
        if scrollView.contentOffset.y > 0 {
            print("向下滑动，scrollView.contentOffset.y = \(scrollView.contentOffset.y) ")
            return false
        }
![image](https://user-images.githubusercontent.com/19849661/110089660-54d7d580-7dd1-11eb-8b64-54737a5fb615.png)

**Comment by yanmingLiu** [comment]
已提交pr

**Comment by Olaf2018** [comment]
双击放大后，拖动至顶，再次拖动可收起图片，这个是定义的交互形式，以避免在拖动中收起了图片。
欢迎对Lantern功能的关注和讨论。
